### ISSUE TITLE
Ignore automatically-generated python directories

### ISSUE THREAD

**Issue by dhimmel** [greenelab/DAPS#1]
Is there a reason why `.ipynb_checkpoints` and `__pycache__` are not in your `.gitingore`?

I usually put ignore these directories. See https://www.gitignore.io/api/ipythonnotebook%2Cpython

**Comment by brettbj** [comment]
I think they may have been re-added in the CI process, will remove them this week

**Comment by brettbj** [comment]
All set now

**Comment by dhimmel** [comment]
Got it -- closed in 0af423ed14ad001a3087f956173a3192e13481af.

Pro tip: You can [autoclose via commit message](https://help.github.com/articles/closing-issues-via-commit-messages/). For example:

```
Closes #1 or Fixes greenelab/DAPS#1
```
