### ISSUE TITLE
Suggestions for improving the GitHub description and website field

### ISSUE THREAD

**Issue by dhimmel** [greenelab/DAPS#2]
Currently, the description and website field for this repository are:

> bioRxiv preprint describing the work in this repository http://biorxiv.org/content/early/2016/02/18/039800

I suggest changing the URL to a DOI link (https://doi.org/10.1101/039800), which will always resolve to the most recent version of the preprint.

Also I think it makes sense to provide a description that is self-sufficient. If you're browsing [Greene Lab repos](https://github.com/greenelab), the current description is unsatisfying. For example, the README title is more informative:

> Denoising Autoencoders for Phenotype Stratification

**Comment by cgreene** [comment]
Much improved - thanks!
